### ISSUE TITLE
Promtimer fails to start on Ubuntu 20+ with package-managed Prometheus due to unknown option --storage.tsdb.no-lockfile

### ISSUE THREAD

**Issue by floriancb** [couchbaselabs/promtimer#42]
Environment:

- Windows 11 WSL2 running Ubuntu 22.04
- Prometheus version 2.31.2+ds1 (branch: debian/sid, revision: 2.31.2+ds1-1ubuntu1)

Running promtimer returns immediately:
```
# promtimer -p /usr/bin/prometheus
using grafana home path:/usr/share/grafana
starting prometheus server on 0.0.0.0:13301 against ./stats_snapshot; logging to .promtimer/logs/prom-..log
starting grafana server (on localhost:13300; logging to .promtimer/logs/grafana.log)
# 
```

Investigating log:
```
# cat .promtimer/logs/prom-..log
Error parsing commandline arguments: unknown long flag '--storage.tsdb.no-lockfile'
prometheus: error: unknown long flag '--storage.tsdb.no-lockfile'
```

Finding the offender:
```
# grep -R storage.tsdb.no-lockfile
promtimer/cbstats.py:                '--storage.tsdb.no-lockfile',
```

Commenting the above line from `cbstats.py` makes things work.

**Comment by dave-finlay** [comment]
Hey Florian - sorry for the super-delayed response. I assume (hope) you were able to work around your issue by removing the offending line. 

As to why you saw this - on that I have no idea. `storage.tsdb.no-lockfile` has been a flag available in every version of Prometheus I've ever used. (Currently I'm on 2.33.) 

This flag appears to have been introduced in 2017 in this patch: https://github.com/prometheus/prometheus/commit/be32afd6df56029737cfafef82990c0cbca712ab

And is still in the code at HEAD today:
https://github.com/prometheus/prometheus/blob/bec68558ba991d28e706d3eaa0b2c4576ab9c9f6/cmd/prometheus/main.go#L325

I'm not quite sure why your version of Prometheus appears not to have this flag. 

Suggest running 
```
prometheus -h
```

And checking the output for the presence of the `storage.tsdb.no-lockfile` option. Perhaps since it's missing there'll be some explanation as to why.

Where did you get this Prometheus from? Did you follow the instructions to install on Ubuntu? 

You could try downloading another binary (from https://prometheus.io/download/) and see if that works. I'd be OK putting in a "don't invoke with the no-lockfile" option to promtimer if we see this is a common situation and can understand why it happens. The reason for the no-lockfile option in the first place is that people often brutally kill promtimer (or it crashes during development) and it's a pain to have to manually clean up the lock files all the time.

**Comment by dave-finlay** [comment]
> I am pretty sure I installed using the Ubuntu package manager. It seems that option does not exist in that

Yes - and it looks like this is the source of the problem.

For some reason, the Ubuntu package management guys have seen fit to disable Prometheus locking by default - along with a host of other patches they apply on top of vanilla prometheus. You can see the list of patches they apply to Prometheus on Ubuntu 22 here:

https://git.launchpad.net/ubuntu/+source/prometheus/log/?h=applied/ubuntu/jammy-devel

Notable among these is this one:

https://git.launchpad.net/ubuntu/+source/prometheus/commit/?h=applied/ubuntu/jammy-devel&id=59e5bfa3d1ac026e008449e382e53694b4d328e9

Unhelpfully, the don't say why they disable the lockfile by default. But I imagine it's for the same reason that we turn it off in Promtimer - for development / single user use cases it's a bit annoying. 

If you google "how to install prometheus on ubuntu", you'll notice that in all cases you'll be advised to use the package manager to install `nginx` and `curl` or `wget` and then download a pre-compiled binary from github and use that rather than use the package manager. Actually, for now this is what I'd recommend you do so you can remove your Promtimer patch and have confidence that you're running the same Prometheus as the rest of us.

That said, it would be nice for Promtimer to handle this missing flag on a platform like Ubuntu. Simply, I think prior to starting prometheus, I'd get the help and check for the presence of the no-lockfile option and only include it if found. I don't have time for it right now, but perhaps I'll find some soon or someone else might to add this.

**Comment by dave-finlay** [comment]
Note also: you don't need to actually _install_ Prometheus to run Promtimer. Downloading the pre-compiled binary and unzipping is sufficient. You can leave your package manager installed Prometheus in place.

**Comment by dave-finlay** [comment]
Should be addressed by https://github.com/couchbaselabs/promtimer/commit/70db6a289866c44d95398c0a9ae2451e58c55462.

@floriancb : if you have time would be great if you could give it a try. If you do and it doesn't work, please let me know.
